# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
      branches: [ "main" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:

    runs-on: windows-latest

    steps:
     - name: Azure login
       uses: azure/login@v2
       with:
         auth-type: IDENTITY
         tenant-id: f8e700e2-5bc3-49fc-9cab-a3ff3c28c23d
         subscription-id: a3737467-953c-4977-8aa1-9c7a6e2d0ff4
         enable-AzPSSession: true
