# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
     - name: Azure login
       uses: azure/login@v2
       with:
          client-id: 69e9508c-65b6-44eb-8405-4fff64537b8f
          tenant-id: 380606ad-5b1b-4d96-b9cc-952db72ace41
          subscription-id: 4c309aaa-c3d0-47b8-b3d1-0feb37a9b284
